config/routes.rb
Rails.application.routes.draw do
  get 'students/list'
  resources :students

  get "student/list" , to: "students#list"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sboy.rb
class Sboy < ApplicationRecord
    
    validates :title, presence: true
    validates :body, presence: true, length: { minimum: 10 }
  end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def list 
    # here @students is a intnance variable and Sboy is a table name(model)
    @students  = Sboy.all
  end

  def show
    @student = Sboy.find(params[:id])
  end

  def new
    @student = Sboy.new
  end

  def create
    @student = Sboy.new(student_params)
    if @student.save
      redirect_to @student
    else
      render :new, status: :unprocessable_entity
    end
  end

  def student_params
    params.require(:student).permit(:title, :body)
  end

  def index
    @students = Sboy.all
  end

  def create
    @students = Sboy.new(article_params)
    if @students.save
      redirect_to @students
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @students = Sboy.find(params[:id])
  end

  def update
    @students = Sboy.find(params[:id])
    if @students.update(article_params)
      redirect_to @students
    else
      render :edit, status: :unprocessable_entity 
    end
  end

  def destroy
    @students = Sboy.find(params[:id])
    @students.destroy
    redirect_to root_path, status: :see_other
  end

  private
    def students_params
      params.require(:students).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Student</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/list.html.erb
<h1>students#index</h1>
<p>Find me in app/views/students/index.html.erb</p>
<h4>Ayush</h4>
<h1>Hello, Rails!</h1>

<h1>Students</h1>

<ul>
<% @students  = Sboy.all %>
  <% @students.each do |student| %>
    <li>
      <a href="<%= student_path(student) %>">
        <%= student.name %>
      </a>
    </li>
  <% end %>
<ul>
  <% @students.each do |student| %>
    <li>
      <%= student.name %>
      <%= student.email %>
    </li>
  <% end %>
</ul> 


<%= link_to "New student", new_student_path %>

app/views/students/new.html.erb
<%= render "form", student: @students %>

app/views/students/show.html.erb
<h1><%= @student.name %></h1>

<p><%= @student.email %></p>

<p><%= @student.mobile %></p>

<p><%= @student.address %></p>
<ul>
  <li><%= link_to "Edit", edit_student_path(@student) %></li>
  <li><%= link_to "Destroy", student_path(@student), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>